//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a {
        ///	color: #06C;
        ///	text-decoration: underline;
        ///}
        ///
        ///a:visited {
        ///	color: #80080;
        ///}
        ///
        ///address {
        ///	display: block;
        ///	font-style: italic;
        ///}
        ///
        ///b {
        ///	font-weight: bold;
        ///}
        ///
        ///bdo {
        ///	direction: rtl;
        ///	unicode-bidi: bidi-override;
        ///}
        ///
        ///blockquote {
        ///	display: block;
        ///	margin: 1em 40px;
        ///}
        ///
        ///body {
        ///	display: block;
        ///	margin: 8px;
        ///	zoom: 1;
        ///	font-size:10pt;
        ///	line-height:12pt;
        ///}
        ///
        ///button {
        ///	background-color: #F0F0F0;
        ///	border-width: 3px;
        ///	box-sizing: border-box;
        ///	font-family: sans-serif;
        ///	font-siz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Base_CSS {
            get {
                return ResourceManager.GetString("Base_CSS", resourceCulture);
            }
        }
    }
}
